/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.NotificationSettingDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NotificationSettingDto', function() {
    it('should create an instance of NotificationSettingDto', function() {
      // uncomment below and update the code to test NotificationSettingDto
      //var instance = new OpenApiDefinition.NotificationSettingDto();
      //expect(instance).to.be.a(OpenApiDefinition.NotificationSettingDto);
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new OpenApiDefinition.NotificationSettingDto();
      //expect(instance).to.be();
    });

    it('should have the property taskEnabled (base name: "taskEnabled")', function() {
      // uncomment below and update the code to test the property taskEnabled
      //var instance = new OpenApiDefinition.NotificationSettingDto();
      //expect(instance).to.be();
    });

    it('should have the property financeEnabled (base name: "financeEnabled")', function() {
      // uncomment below and update the code to test the property financeEnabled
      //var instance = new OpenApiDefinition.NotificationSettingDto();
      //expect(instance).to.be();
    });

    it('should have the property penaltyEnabled (base name: "penaltyEnabled")', function() {
      // uncomment below and update the code to test the property penaltyEnabled
      //var instance = new OpenApiDefinition.NotificationSettingDto();
      //expect(instance).to.be();
    });

    it('should have the property ruleEnabled (base name: "ruleEnabled")', function() {
      // uncomment below and update the code to test the property ruleEnabled
      //var instance = new OpenApiDefinition.NotificationSettingDto();
      //expect(instance).to.be();
    });

    it('should have the property userEnabled (base name: "userEnabled")', function() {
      // uncomment below and update the code to test the property userEnabled
      //var instance = new OpenApiDefinition.NotificationSettingDto();
      //expect(instance).to.be();
    });

  });

}));
