/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreatePenaltyRequest model module.
 * @module model/CreatePenaltyRequest
 * @version v0
 */
class CreatePenaltyRequest {
    /**
     * Constructs a new <code>CreatePenaltyRequest</code>.
     * @alias module:model/CreatePenaltyRequest
     */
    constructor() { 
        
        CreatePenaltyRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreatePenaltyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePenaltyRequest} obj Optional instance to populate.
     * @return {module:model/CreatePenaltyRequest} The populated <code>CreatePenaltyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePenaltyRequest();

            if (data.hasOwnProperty('apartmentId')) {
                obj['apartmentId'] = ApiClient.convertToType(data['apartmentId'], 'String');
            }
            if (data.hasOwnProperty('assignedTo')) {
                obj['assignedTo'] = ApiClient.convertToType(data['assignedTo'], 'String');
            }
            if (data.hasOwnProperty('ruleId')) {
                obj['ruleId'] = ApiClient.convertToType(data['ruleId'], 'String');
            }
            if (data.hasOwnProperty('fineAmount')) {
                obj['fineAmount'] = ApiClient.convertToType(data['fineAmount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreatePenaltyRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreatePenaltyRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['apartmentId'] && !(typeof data['apartmentId'] === 'string' || data['apartmentId'] instanceof String)) {
            throw new Error("Expected the field `apartmentId` to be a primitive type in the JSON string but got " + data['apartmentId']);
        }
        // ensure the json data is a string
        if (data['assignedTo'] && !(typeof data['assignedTo'] === 'string' || data['assignedTo'] instanceof String)) {
            throw new Error("Expected the field `assignedTo` to be a primitive type in the JSON string but got " + data['assignedTo']);
        }
        // ensure the json data is a string
        if (data['ruleId'] && !(typeof data['ruleId'] === 'string' || data['ruleId'] instanceof String)) {
            throw new Error("Expected the field `ruleId` to be a primitive type in the JSON string but got " + data['ruleId']);
        }

        return true;
    }


}



/**
 * @member {String} apartmentId
 */
CreatePenaltyRequest.prototype['apartmentId'] = undefined;

/**
 * @member {String} assignedTo
 */
CreatePenaltyRequest.prototype['assignedTo'] = undefined;

/**
 * @member {String} ruleId
 */
CreatePenaltyRequest.prototype['ruleId'] = undefined;

/**
 * @member {Number} fineAmount
 */
CreatePenaltyRequest.prototype['fineAmount'] = undefined;






export default CreatePenaltyRequest;

