/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RuleDto from './RuleDto';
import UserInfoDto from './UserInfoDto';

/**
 * The PenaltyResponse model module.
 * @module model/PenaltyResponse
 * @version v0
 */
class PenaltyResponse {
    /**
     * Constructs a new <code>PenaltyResponse</code>.
     * @alias module:model/PenaltyResponse
     */
    constructor() { 
        
        PenaltyResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PenaltyResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PenaltyResponse} obj Optional instance to populate.
     * @return {module:model/PenaltyResponse} The populated <code>PenaltyResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PenaltyResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = UserInfoDto.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('rule')) {
                obj['rule'] = RuleDto.constructFromObject(data['rule']);
            }
            if (data.hasOwnProperty('fineAmount')) {
                obj['fineAmount'] = ApiClient.convertToType(data['fineAmount'], 'Number');
            }
            if (data.hasOwnProperty('assignedDate')) {
                obj['assignedDate'] = ApiClient.convertToType(data['assignedDate'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PenaltyResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PenaltyResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          UserInfoDto.validateJSON(data['user']);
        }
        // validate the optional field `rule`
        if (data['rule']) { // data not null
          RuleDto.validateJSON(data['rule']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
PenaltyResponse.prototype['id'] = undefined;

/**
 * @member {module:model/UserInfoDto} user
 */
PenaltyResponse.prototype['user'] = undefined;

/**
 * @member {module:model/RuleDto} rule
 */
PenaltyResponse.prototype['rule'] = undefined;

/**
 * @member {Number} fineAmount
 */
PenaltyResponse.prototype['fineAmount'] = undefined;

/**
 * @member {Date} assignedDate
 */
PenaltyResponse.prototype['assignedDate'] = undefined;

/**
 * @member {module:model/PenaltyResponse.StatusEnum} status
 */
PenaltyResponse.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
PenaltyResponse['StatusEnum'] = {

    /**
     * value: "PAID"
     * @const
     */
    "PAID": "PAID",

    /**
     * value: "UNPAID"
     * @const
     */
    "UNPAID": "UNPAID"
};



export default PenaltyResponse;

