/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PenaltyDto model module.
 * @module model/PenaltyDto
 * @version v0
 */
class PenaltyDto {
    /**
     * Constructs a new <code>PenaltyDto</code>.
     * @alias module:model/PenaltyDto
     */
    constructor() { 
        
        PenaltyDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PenaltyDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PenaltyDto} obj Optional instance to populate.
     * @return {module:model/PenaltyDto} The populated <code>PenaltyDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PenaltyDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('apartmentId')) {
                obj['apartmentId'] = ApiClient.convertToType(data['apartmentId'], 'String');
            }
            if (data.hasOwnProperty('assignedTo')) {
                obj['assignedTo'] = ApiClient.convertToType(data['assignedTo'], 'String');
            }
            if (data.hasOwnProperty('ruleId')) {
                obj['ruleId'] = ApiClient.convertToType(data['ruleId'], 'String');
            }
            if (data.hasOwnProperty('fineAmount')) {
                obj['fineAmount'] = ApiClient.convertToType(data['fineAmount'], 'Number');
            }
            if (data.hasOwnProperty('assignedDate')) {
                obj['assignedDate'] = ApiClient.convertToType(data['assignedDate'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PenaltyDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PenaltyDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['apartmentId'] && !(typeof data['apartmentId'] === 'string' || data['apartmentId'] instanceof String)) {
            throw new Error("Expected the field `apartmentId` to be a primitive type in the JSON string but got " + data['apartmentId']);
        }
        // ensure the json data is a string
        if (data['assignedTo'] && !(typeof data['assignedTo'] === 'string' || data['assignedTo'] instanceof String)) {
            throw new Error("Expected the field `assignedTo` to be a primitive type in the JSON string but got " + data['assignedTo']);
        }
        // ensure the json data is a string
        if (data['ruleId'] && !(typeof data['ruleId'] === 'string' || data['ruleId'] instanceof String)) {
            throw new Error("Expected the field `ruleId` to be a primitive type in the JSON string but got " + data['ruleId']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
PenaltyDto.prototype['id'] = undefined;

/**
 * @member {String} apartmentId
 */
PenaltyDto.prototype['apartmentId'] = undefined;

/**
 * @member {String} assignedTo
 */
PenaltyDto.prototype['assignedTo'] = undefined;

/**
 * @member {String} ruleId
 */
PenaltyDto.prototype['ruleId'] = undefined;

/**
 * @member {Number} fineAmount
 */
PenaltyDto.prototype['fineAmount'] = undefined;

/**
 * @member {Date} assignedDate
 */
PenaltyDto.prototype['assignedDate'] = undefined;

/**
 * @member {module:model/PenaltyDto.StatusEnum} status
 */
PenaltyDto.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
PenaltyDto['StatusEnum'] = {

    /**
     * value: "PAID"
     * @const
     */
    "PAID": "PAID",

    /**
     * value: "UNPAID"
     * @const
     */
    "UNPAID": "UNPAID"
};



export default PenaltyDto;

