/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateExpenseRequest model module.
 * @module model/CreateExpenseRequest
 * @version v0
 */
class CreateExpenseRequest {
    /**
     * Constructs a new <code>CreateExpenseRequest</code>.
     * @alias module:model/CreateExpenseRequest
     */
    constructor() { 
        
        CreateExpenseRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateExpenseRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateExpenseRequest} obj Optional instance to populate.
     * @return {module:model/CreateExpenseRequest} The populated <code>CreateExpenseRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateExpenseRequest();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('photoBase64')) {
                obj['photoBase64'] = ApiClient.convertToType(data['photoBase64'], 'String');
            }
            if (data.hasOwnProperty('itemId')) {
                obj['itemId'] = ApiClient.convertToType(data['itemId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateExpenseRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateExpenseRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['photoBase64'] && !(typeof data['photoBase64'] === 'string' || data['photoBase64'] instanceof String)) {
            throw new Error("Expected the field `photoBase64` to be a primitive type in the JSON string but got " + data['photoBase64']);
        }
        // ensure the json data is a string
        if (data['itemId'] && !(typeof data['itemId'] === 'string' || data['itemId'] instanceof String)) {
            throw new Error("Expected the field `itemId` to be a primitive type in the JSON string but got " + data['itemId']);
        }

        return true;
    }


}



/**
 * @member {Number} amount
 */
CreateExpenseRequest.prototype['amount'] = undefined;

/**
 * @member {String} description
 */
CreateExpenseRequest.prototype['description'] = undefined;

/**
 * @member {String} photoBase64
 */
CreateExpenseRequest.prototype['photoBase64'] = undefined;

/**
 * @member {String} itemId
 */
CreateExpenseRequest.prototype['itemId'] = undefined;






export default CreateExpenseRequest;

