/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.PenaltyResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PenaltyResponse', function() {
    it('should create an instance of PenaltyResponse', function() {
      // uncomment below and update the code to test PenaltyResponse
      //var instance = new OpenApiDefinition.PenaltyResponse();
      //expect(instance).to.be.a(OpenApiDefinition.PenaltyResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenApiDefinition.PenaltyResponse();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new OpenApiDefinition.PenaltyResponse();
      //expect(instance).to.be();
    });

    it('should have the property rule (base name: "rule")', function() {
      // uncomment below and update the code to test the property rule
      //var instance = new OpenApiDefinition.PenaltyResponse();
      //expect(instance).to.be();
    });

    it('should have the property fineAmount (base name: "fineAmount")', function() {
      // uncomment below and update the code to test the property fineAmount
      //var instance = new OpenApiDefinition.PenaltyResponse();
      //expect(instance).to.be();
    });

    it('should have the property assignedDate (base name: "assignedDate")', function() {
      // uncomment below and update the code to test the property assignedDate
      //var instance = new OpenApiDefinition.PenaltyResponse();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new OpenApiDefinition.PenaltyResponse();
      //expect(instance).to.be();
    });

  });

}));
