/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VoteDto model module.
 * @module model/VoteDto
 * @version v0
 */
class VoteDto {
    /**
     * Constructs a new <code>VoteDto</code>.
     * @alias module:model/VoteDto
     */
    constructor() { 
        
        VoteDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VoteDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VoteDto} obj Optional instance to populate.
     * @return {module:model/VoteDto} The populated <code>VoteDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VoteDto();

            if (data.hasOwnProperty('ruleId')) {
                obj['ruleId'] = ApiClient.convertToType(data['ruleId'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('vote')) {
                obj['vote'] = ApiClient.convertToType(data['vote'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VoteDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VoteDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ruleId'] && !(typeof data['ruleId'] === 'string' || data['ruleId'] instanceof String)) {
            throw new Error("Expected the field `ruleId` to be a primitive type in the JSON string but got " + data['ruleId']);
        }
        // ensure the json data is a string
        if (data['userId'] && !(typeof data['userId'] === 'string' || data['userId'] instanceof String)) {
            throw new Error("Expected the field `userId` to be a primitive type in the JSON string but got " + data['userId']);
        }
        // ensure the json data is a string
        if (data['vote'] && !(typeof data['vote'] === 'string' || data['vote'] instanceof String)) {
            throw new Error("Expected the field `vote` to be a primitive type in the JSON string but got " + data['vote']);
        }

        return true;
    }


}



/**
 * @member {String} ruleId
 */
VoteDto.prototype['ruleId'] = undefined;

/**
 * @member {String} userId
 */
VoteDto.prototype['userId'] = undefined;

/**
 * @member {module:model/VoteDto.VoteEnum} vote
 */
VoteDto.prototype['vote'] = undefined;





/**
 * Allowed values for the <code>vote</code> property.
 * @enum {String}
 * @readonly
 */
VoteDto['VoteEnum'] = {

    /**
     * value: "FOR"
     * @const
     */
    "FOR": "FOR",

    /**
     * value: "AGAINST"
     * @const
     */
    "AGAINST": "AGAINST"
};



export default VoteDto;

