/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserInfoDto from './UserInfoDto';

/**
 * The ApartmentInfo model module.
 * @module model/ApartmentInfo
 * @version v0
 */
class ApartmentInfo {
    /**
     * Constructs a new <code>ApartmentInfo</code>.
     * @alias module:model/ApartmentInfo
     */
    constructor() { 
        
        ApartmentInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApartmentInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApartmentInfo} obj Optional instance to populate.
     * @return {module:model/ApartmentInfo} The populated <code>ApartmentInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApartmentInfo();

            if (data.hasOwnProperty('apartmentId')) {
                obj['apartmentId'] = ApiClient.convertToType(data['apartmentId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], [UserInfoDto]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApartmentInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApartmentInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['apartmentId'] && !(typeof data['apartmentId'] === 'string' || data['apartmentId'] instanceof String)) {
            throw new Error("Expected the field `apartmentId` to be a primitive type in the JSON string but got " + data['apartmentId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        if (data['users']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['users'])) {
                throw new Error("Expected the field `users` to be an array in the JSON data but got " + data['users']);
            }
            // validate the optional field `users` (array)
            for (const item of data['users']) {
                UserInfoDto.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} apartmentId
 */
ApartmentInfo.prototype['apartmentId'] = undefined;

/**
 * @member {String} name
 */
ApartmentInfo.prototype['name'] = undefined;

/**
 * @member {String} address
 */
ApartmentInfo.prototype['address'] = undefined;

/**
 * @member {Array.<module:model/UserInfoDto>} users
 */
ApartmentInfo.prototype['users'] = undefined;






export default ApartmentInfo;

