/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateUserProfileRequest model module.
 * @module model/UpdateUserProfileRequest
 * @version v0
 */
class UpdateUserProfileRequest {
    /**
     * Constructs a new <code>UpdateUserProfileRequest</code>.
     * @alias module:model/UpdateUserProfileRequest
     */
    constructor() { 
        
        UpdateUserProfileRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateUserProfileRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateUserProfileRequest} obj Optional instance to populate.
     * @return {module:model/UpdateUserProfileRequest} The populated <code>UpdateUserProfileRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateUserProfileRequest();

            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('profilePictureBase64')) {
                obj['profilePictureBase64'] = ApiClient.convertToType(data['profilePictureBase64'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateUserProfileRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateUserProfileRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['profilePictureBase64'] && !(typeof data['profilePictureBase64'] === 'string' || data['profilePictureBase64'] instanceof String)) {
            throw new Error("Expected the field `profilePictureBase64` to be a primitive type in the JSON string but got " + data['profilePictureBase64']);
        }

        return true;
    }


}



/**
 * @member {String} firstName
 */
UpdateUserProfileRequest.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
UpdateUserProfileRequest.prototype['lastName'] = undefined;

/**
 * @member {String} email
 */
UpdateUserProfileRequest.prototype['email'] = undefined;

/**
 * @member {module:model/UpdateUserProfileRequest.StatusEnum} status
 */
UpdateUserProfileRequest.prototype['status'] = undefined;

/**
 * @member {String} profilePictureBase64
 */
UpdateUserProfileRequest.prototype['profilePictureBase64'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
UpdateUserProfileRequest['StatusEnum'] = {

    /**
     * value: "ACTIVE"
     * @const
     */
    "ACTIVE": "ACTIVE",

    /**
     * value: "AWAY"
     * @const
     */
    "AWAY": "AWAY",

    /**
     * value: "SICK"
     * @const
     */
    "SICK": "SICK"
};



export default UpdateUserProfileRequest;

