/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UseInviteCodeRequest model module.
 * @module model/UseInviteCodeRequest
 * @version v0
 */
class UseInviteCodeRequest {
    /**
     * Constructs a new <code>UseInviteCodeRequest</code>.
     * @alias module:model/UseInviteCodeRequest
     */
    constructor() { 
        
        UseInviteCodeRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UseInviteCodeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UseInviteCodeRequest} obj Optional instance to populate.
     * @return {module:model/UseInviteCodeRequest} The populated <code>UseInviteCodeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UseInviteCodeRequest();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UseInviteCodeRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UseInviteCodeRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} code
 */
UseInviteCodeRequest.prototype['code'] = undefined;






export default UseInviteCodeRequest;

