/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NotificationSettingDto model module.
 * @module model/NotificationSettingDto
 * @version v0
 */
class NotificationSettingDto {
    /**
     * Constructs a new <code>NotificationSettingDto</code>.
     * @alias module:model/NotificationSettingDto
     */
    constructor() { 
        
        NotificationSettingDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NotificationSettingDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NotificationSettingDto} obj Optional instance to populate.
     * @return {module:model/NotificationSettingDto} The populated <code>NotificationSettingDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NotificationSettingDto();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('taskEnabled')) {
                obj['taskEnabled'] = ApiClient.convertToType(data['taskEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('financeEnabled')) {
                obj['financeEnabled'] = ApiClient.convertToType(data['financeEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('penaltyEnabled')) {
                obj['penaltyEnabled'] = ApiClient.convertToType(data['penaltyEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('ruleEnabled')) {
                obj['ruleEnabled'] = ApiClient.convertToType(data['ruleEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('userEnabled')) {
                obj['userEnabled'] = ApiClient.convertToType(data['userEnabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NotificationSettingDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NotificationSettingDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['userId'] && !(typeof data['userId'] === 'string' || data['userId'] instanceof String)) {
            throw new Error("Expected the field `userId` to be a primitive type in the JSON string but got " + data['userId']);
        }

        return true;
    }


}



/**
 * @member {String} userId
 */
NotificationSettingDto.prototype['userId'] = undefined;

/**
 * @member {Boolean} taskEnabled
 */
NotificationSettingDto.prototype['taskEnabled'] = undefined;

/**
 * @member {Boolean} financeEnabled
 */
NotificationSettingDto.prototype['financeEnabled'] = undefined;

/**
 * @member {Boolean} penaltyEnabled
 */
NotificationSettingDto.prototype['penaltyEnabled'] = undefined;

/**
 * @member {Boolean} ruleEnabled
 */
NotificationSettingDto.prototype['ruleEnabled'] = undefined;

/**
 * @member {Boolean} userEnabled
 */
NotificationSettingDto.prototype['userEnabled'] = undefined;






export default NotificationSettingDto;

