/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddToApartmentResponse from './model/AddToApartmentResponse';
import ApartmentInfo from './model/ApartmentInfo';
import AuthRequest from './model/AuthRequest';
import ChangePasswordRequest from './model/ChangePasswordRequest';
import CreateApartmentRequest from './model/CreateApartmentRequest';
import CreateApartmentResponse from './model/CreateApartmentResponse';
import GetApartmentResponse from './model/GetApartmentResponse';
import GetUserResponse from './model/GetUserResponse';
import RefreshTokenRequest from './model/RefreshTokenRequest';
import TokenResponse from './model/TokenResponse';
import UpdateApartmentRequest from './model/UpdateApartmentRequest';
import UpdateApartmentResponse from './model/UpdateApartmentResponse';
import UserInfoDto from './model/UserInfoDto';
import UserRegistrationRequest from './model/UserRegistrationRequest';
import UserResponse from './model/UserResponse';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddToApartmentResponse model constructor.
     * @property {module:model/AddToApartmentResponse}
     */
    AddToApartmentResponse,

    /**
     * The ApartmentInfo model constructor.
     * @property {module:model/ApartmentInfo}
     */
    ApartmentInfo,

    /**
     * The AuthRequest model constructor.
     * @property {module:model/AuthRequest}
     */
    AuthRequest,

    /**
     * The ChangePasswordRequest model constructor.
     * @property {module:model/ChangePasswordRequest}
     */
    ChangePasswordRequest,

    /**
     * The CreateApartmentRequest model constructor.
     * @property {module:model/CreateApartmentRequest}
     */
    CreateApartmentRequest,

    /**
     * The CreateApartmentResponse model constructor.
     * @property {module:model/CreateApartmentResponse}
     */
    CreateApartmentResponse,

    /**
     * The GetApartmentResponse model constructor.
     * @property {module:model/GetApartmentResponse}
     */
    GetApartmentResponse,

    /**
     * The GetUserResponse model constructor.
     * @property {module:model/GetUserResponse}
     */
    GetUserResponse,

    /**
     * The RefreshTokenRequest model constructor.
     * @property {module:model/RefreshTokenRequest}
     */
    RefreshTokenRequest,

    /**
     * The TokenResponse model constructor.
     * @property {module:model/TokenResponse}
     */
    TokenResponse,

    /**
     * The UpdateApartmentRequest model constructor.
     * @property {module:model/UpdateApartmentRequest}
     */
    UpdateApartmentRequest,

    /**
     * The UpdateApartmentResponse model constructor.
     * @property {module:model/UpdateApartmentResponse}
     */
    UpdateApartmentResponse,

    /**
     * The UserInfoDto model constructor.
     * @property {module:model/UserInfoDto}
     */
    UserInfoDto,

    /**
     * The UserRegistrationRequest model constructor.
     * @property {module:model/UserRegistrationRequest}
     */
    UserRegistrationRequest,

    /**
     * The UserResponse model constructor.
     * @property {module:model/UserResponse}
     */
    UserResponse,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
