/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateTaskRequest model module.
 * @module model/CreateTaskRequest
 * @version v0
 */
class CreateTaskRequest {
    /**
     * Constructs a new <code>CreateTaskRequest</code>.
     * @alias module:model/CreateTaskRequest
     * @param apartmentId {String} 
     * @param scheduledAt {Date} 
     */
    constructor(apartmentId, scheduledAt) { 
        
        CreateTaskRequest.initialize(this, apartmentId, scheduledAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, apartmentId, scheduledAt) { 
        obj['apartmentId'] = apartmentId;
        obj['scheduledAt'] = scheduledAt;
    }

    /**
     * Constructs a <code>CreateTaskRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateTaskRequest} obj Optional instance to populate.
     * @return {module:model/CreateTaskRequest} The populated <code>CreateTaskRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateTaskRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('apartmentId')) {
                obj['apartmentId'] = ApiClient.convertToType(data['apartmentId'], 'String');
            }
            if (data.hasOwnProperty('ruleId')) {
                obj['ruleId'] = ApiClient.convertToType(data['ruleId'], 'String');
            }
            if (data.hasOwnProperty('scheduledAt')) {
                obj['scheduledAt'] = ApiClient.convertToType(data['scheduledAt'], 'Date');
            }
            if (data.hasOwnProperty('assignedTo')) {
                obj['assignedTo'] = ApiClient.convertToType(data['assignedTo'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateTaskRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateTaskRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateTaskRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['apartmentId'] && !(typeof data['apartmentId'] === 'string' || data['apartmentId'] instanceof String)) {
            throw new Error("Expected the field `apartmentId` to be a primitive type in the JSON string but got " + data['apartmentId']);
        }
        // ensure the json data is a string
        if (data['ruleId'] && !(typeof data['ruleId'] === 'string' || data['ruleId'] instanceof String)) {
            throw new Error("Expected the field `ruleId` to be a primitive type in the JSON string but got " + data['ruleId']);
        }
        // ensure the json data is a string
        if (data['assignedTo'] && !(typeof data['assignedTo'] === 'string' || data['assignedTo'] instanceof String)) {
            throw new Error("Expected the field `assignedTo` to be a primitive type in the JSON string but got " + data['assignedTo']);
        }

        return true;
    }


}

CreateTaskRequest.RequiredProperties = ["apartmentId", "scheduledAt"];

/**
 * @member {String} title
 */
CreateTaskRequest.prototype['title'] = undefined;

/**
 * @member {String} description
 */
CreateTaskRequest.prototype['description'] = undefined;

/**
 * @member {module:model/CreateTaskRequest.StatusEnum} status
 */
CreateTaskRequest.prototype['status'] = undefined;

/**
 * @member {String} apartmentId
 */
CreateTaskRequest.prototype['apartmentId'] = undefined;

/**
 * @member {String} ruleId
 */
CreateTaskRequest.prototype['ruleId'] = undefined;

/**
 * @member {Date} scheduledAt
 */
CreateTaskRequest.prototype['scheduledAt'] = undefined;

/**
 * @member {String} assignedTo
 */
CreateTaskRequest.prototype['assignedTo'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CreateTaskRequest['StatusEnum'] = {

    /**
     * value: "CREATED"
     * @const
     */
    "CREATED": "CREATED",

    /**
     * value: "IN_PROGRESS"
     * @const
     */
    "IN_PROGRESS": "IN_PROGRESS",

    /**
     * value: "COMPLETED"
     * @const
     */
    "COMPLETED": "COMPLETED",

    /**
     * value: "CANCELED"
     * @const
     */
    "CANCELED": "CANCELED"
};



export default CreateTaskRequest;

