name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Событие триггерится при пуше в ветку main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:${{ github.sha }} .

      # Шаг 4: Пуш Docker-образа в Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:${{ github.sha }}

      # Шаг 5: (Опционально) Пуш Docker-образа с тегом "latest"
      - name: Tag and push latest
        if: github.ref_name == 'main' # Только для ветки main
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:latest
