name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:${{ github.sha }}

      - name: Tag and push latest
        if: github.ref_name == 'main'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image on server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:latest"

      - name: Stop and remove old container
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "docker stop fe-${{ secrets.FE_PROJECT_NAME }} || true && docker rm fe-${{ secrets.FE_PROJECT_NAME }} || true"

      - name: Run new container
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "docker run -d --name fe-${{ secrets.FE_PROJECT_NAME }} -p 80:4173 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:latest"

