name: CI/CD

on:
  push:
    branches:
      - main # Событие триггерится при пуше в ветку main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:${{ github.sha }} .

      # Шаг 4: Пуш Docker-образа в Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:${{ github.sha }}

      # Шаг 5: (Опционально) Пуш Docker-образа с тегом "latest"
      - name: Tag and push latest
        if: github.ref_name == 'main'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # Выполняется после завершения push

    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Шаг 2: Деплой на сервер
      - name: Deploy to server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:latest
            docker stop fe-${{ secrets.FE_PROJECT_NAME }} || true
            docker rm fe-${{ secrets.FE_PROJECT_NAME }} || true
            docker run -d --name fe-${{ secrets.FE_PROJECT_NAME }} -p 80:4173 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FE_PROJECT_NAME }}:latest
          EOF
